notifications:
  email: false

sudo: false

language: php

php:
  - 7.1

branches:
  only:
    - master

cache:
  directories:
    - vendor

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer install --no-progress --no-suggest

before_script:
  - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials

  - git clone --depth=1 https://github.com/250/Steam-data.git ${datadir=~/Steam-data}
      -c user.name=Travis
      -c user.email=bilge+travis@scriptfusion.com
      -c credential.helper=store

  - git clone --depth=1 -b ${branch=gh-pages} https://github.com/$TRAVIS_REPO_SLUG ${out=~/$branch}
      -c user.name=Travis
      -c user.email=bilge+travis@scriptfusion.com
      -c credential.helper=store
  - cd "$out" && pwd || exit
  - rm -rfv * &&
    cp -va "$TRAVIS_BUILD_DIR"/site/* . &&
    cd -

script:
  - db=$datadir/$("$datadir/bin/latest") prevdb=$datadir/$("$datadir/bin/latest" -1)
  - 'echo "db: \"$db\" prevdb: \"$prevdb\""'
  - bin/generate site --min --ext '' --prev-db "$prevdb" "$db" "$out" || exit

  - cd "$out" &&
    git add -A . &&
    git commit -m "Built from $TRAVIS_COMMIT." &&
    [[ -r index.html ]] && git push origin HEAD:$branch

after_script:
  - cd "$datadir" &&
    git commit -am "Added ranks for $TRAVIS_COMMIT." &&
    git push
