name: Build Storybook

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 250/Storybook
          path: sb
          token: ${{ secrets.GH_BILGE_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Cache PHP dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

      - name: Build Storybook
        run: yarn && yarn build-storybook

      - name: Link Storybook
        run: rm -rfv sb/* && cp -val storybook-static/* sb

      - name: Declare CNAME
        run: echo ui.steam250.com > sb/CNAME

      - name: Push site
        run: |
          # Abort if no changes.
          git diff --quiet && exit

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A . &&
          git commit -m "Built from $GITHUB_SHA." &&
          [[ -r CNAME && -r index.html ]] && git push
        working-directory: sb
